### ISSUE TITLE
Project Roadmap

### ISSUE THREAD

**Issue by liuzl** [crawlerclub/x#1]
- [x] Single Machine Demo
- [x] Downloader
  - [x] http downloader
- [ ] Parser
  - [x] html parser, using xpath
  - [x] json parser, mainly for restful api crawling
  - [ ] content parser, main content (title/content/time) extraction, mainly for news articles
- [x] Crawler
- [x] Controller
- [x] Crawler Conf Editor, web based json editor
- [ ] Task Priority (Crawler level)
- [ ] Dashboard
